name: wam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pillow>=8.3.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - pip
  - pip:
    - opencv-python>=4.5.0
    - ptwt>=0.1.0
    - timm>=0.6.0 